// Test entry point. Add each suite's run function here.
runWindowInfoTests()
runKeyboardShortcutTests()
runSwitcherSessionTests()
runPreferencesTests()
runWindowEnumeratorTests()
runMRUTrackerTests()
runSemanticVersionTests()
runL10nTests()
TestRun.shared.finish()
